jdbcSettings:
  url: "jdbc:mysql://localhost:3306/albert"
  username: "root"
  password: ""
  driverClassName: "com.mysql.jdbc.Driver"

#tableScanMode: RuleBased
#tableScanRules:
#  - tableNames: ["main_user"]

packageName: "youxianqi.yixi.model"

# https://github.com/smartnews/jpa-entity-generator
